### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by fotisj** [salesforce/booksum#1]
Got an error collecting the cliffnotes summaries (see below). Looks as if there is a problem, when some element (here article) is missing: 

```>>> 26. Antony and Cleopatra <<<
Traceback (most recent call last):
  File "scripts/data_collection/cliffnotes/get_summaries.py", line 95, in <module>
    section_paragraphs = list(filter(None, scrape_section_continuation(soup, section_header)))
  File "scripts/data_collection/cliffnotes/get_summaries.py", line 41, in scrape_section_continuation
    section_paragraphs = [paragraph.text.strip() for paragraph in section_data.findAll("p", recursive=False)]
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by muggin** [comment]
Thank you for creating the issue, we will look into it as soon as possible.

**Comment by jigsaw2212** [comment]
@fotisj we've fixed this issue with collecting cliffnotes data. Thanks for bringing this to our attention.
